<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <JellyfinVersion Condition="'$(JellyfinVersion)' == ''">12.0</JellyfinVersion>
    <RootNamespace>Jellyfin.Plugin.Ronin</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <AnalysisMode>Default</AnalysisMode>
    <CodeAnalysisRuleSet>../jellyfin.ruleset</CodeAnalysisRuleSet>
    <AssemblyVersion>1.0.7.2</AssemblyVersion>
    <Version>1.0.0.1</Version>
  </PropertyGroup>

  <PropertyGroup Condition="$(JellyfinVersion.StartsWith('12.'))">
    <TargetFramework>net10.0</TargetFramework>
    <JellyfinPackageVersion>12.0.0-rc2</JellyfinPackageVersion>
  </PropertyGroup>
  <PropertyGroup Condition="$(JellyfinVersion.StartsWith('10.11'))">
    <TargetFramework>net9.0</TargetFramework>
    <JellyfinPackageVersion>10.11.0</JellyfinPackageVersion>
  </PropertyGroup>
  <PropertyGroup Condition="$(JellyfinVersion.StartsWith('10.10'))">
    <TargetFramework>net8.0</TargetFramework>
    <JellyfinPackageVersion>10.10.7</JellyfinPackageVersion>
    <DefineConstants>$(DefineConstants);JELLYFIN_10_10</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinPackageVersion)" >
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Jellyfin.Model" Version="$(JellyfinPackageVersion)">
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.71" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3">
      <Private>false</Private>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Jellyfin.Plugin.Ronin.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Configuration\configPage.html" />
    <EmbeddedResource Include="Configuration\configPage.html" />
    <None Remove="Inject\ronin.css" />
    <EmbeddedResource Include="Inject\ronin.css" />
    <None Remove="Inject\ronin.js" />
    <EmbeddedResource Include="Inject\ronin.js" />
    <None Remove="Inject\ronin-hideseasons.js" />
    <EmbeddedResource Include="Inject\ronin-hideseasons.js" />
    <None Include="..\Images\logo.jpg" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>